/*
    Emits a data-only INSERT script for the whole library database.

    Schema is not scripted: the application creates it with EF migrations on first start, so
    scripting it too would risk the two disagreeing. This produces only the rows.

    Three things this has to get right, and each is a way a hand-written script goes wrong:

      * Order. Rows must arrive after anything they point at, or the foreign keys reject them.
        Tables are sorted by dependency depth rather than by name.

      * Identity columns. Book 12 has to stay book 12, because the copies, tags and loans all
        reference it. IDENTITY_INSERT is toggled per table so the original keys survive.

      * Types. rowversion is generated by the server and cannot be inserted; computed columns
        likewise. Strings need doubling of quotes, binary needs 0x form, dates need a culture
        independent format. Everything is emitted through the type checks below rather than by
        string-concatenating whatever CAST produces.

    Usage:
        sqlcmd -S .\SQLEXPRESS -d SMA_LMS -i tools/generate-data-script.sql -o data.sql -h -1 -W -y 0
*/

SET NOCOUNT ON;

DECLARE @out TABLE (Seq INT IDENTITY(1,1), Line NVARCHAR(MAX));

INSERT INTO @out (Line) VALUES
    ('/* SMA Library data. Generated from the working database. */'),
    ('SET NOCOUNT ON;'),
    -- Required, not decoration: BookRfidTags and StudentRfidTags carry unique filtered
    -- indexes, and SQL Server refuses to insert into such a table unless these are ON.
    -- sqlcmd does not set them for a script run with -i.
    ('SET QUOTED_IDENTIFIER ON;'),
    ('SET ANSI_NULLS ON;'),
    ('SET XACT_ABORT ON;'),
    ('BEGIN TRANSACTION;'),
    ('');

/* ---- dependency order -------------------------------------------------
   Depth 0 is a table that references nothing; each level after it may only
   reference tables already emitted. Self-references are ignored, or a table
   that points at itself would never be orderable. */
WITH FkEdges AS (
    SELECT DISTINCT
           parent_object_id  AS ChildId,
           referenced_object_id AS ParentId
    FROM sys.foreign_keys
    WHERE parent_object_id <> referenced_object_id
),
Depth AS (
    SELECT t.object_id, 0 AS Lvl
    FROM sys.tables t
    WHERE NOT EXISTS (SELECT 1 FROM FkEdges e WHERE e.ChildId = t.object_id)

    UNION ALL

    SELECT e.ChildId, d.Lvl + 1
    FROM FkEdges e
    JOIN Depth d ON d.object_id = e.ParentId
),
Ordered AS (
    SELECT object_id, MAX(Lvl) AS Lvl
    FROM Depth
    GROUP BY object_id
)
SELECT t.name AS TableName, o.Lvl
INTO #Plan
FROM Ordered o
JOIN sys.tables t ON t.object_id = o.object_id
WHERE t.name <> '__EFMigrationsHistory'
OPTION (MAXRECURSION 100);

/* ---- clear-down ------------------------------------------------------
   The application seeds roles, policies and the reader row while it starts, so a restore that
   only inserted would collide on the first unique index it met. Emitted in reverse dependency
   order: children before the parents they reference. Only tables this script actually
   repopulates are touched - anything else is left as the application made it. */
DECLARE @del SYSNAME;

INSERT INTO @out (Line) VALUES ('/* Replace, not append: clear what these tables hold first. */');

DECLARE del_cursor CURSOR LOCAL FAST_FORWARD FOR
    SELECT p.TableName
    FROM #Plan p
    WHERE EXISTS (
        SELECT 1 FROM sys.tables t
        JOIN sys.partitions pa ON pa.object_id = t.object_id AND pa.index_id IN (0,1)
        WHERE t.name = p.TableName GROUP BY t.name HAVING SUM(pa.rows) > 0)
    ORDER BY p.Lvl DESC, p.TableName;

OPEN del_cursor;
FETCH NEXT FROM del_cursor INTO @del;
WHILE @@FETCH_STATUS = 0
BEGIN
    INSERT INTO @out (Line) VALUES ('DELETE FROM ' + QUOTENAME(@del) + ';');
    FETCH NEXT FROM del_cursor INTO @del;
END
CLOSE del_cursor;
DEALLOCATE del_cursor;

INSERT INTO @out (Line) VALUES ('');

DECLARE @table SYSNAME, @lvl INT;

DECLARE plan_cursor CURSOR LOCAL FAST_FORWARD FOR
    SELECT TableName, Lvl FROM #Plan ORDER BY Lvl, TableName;

OPEN plan_cursor;
FETCH NEXT FROM plan_cursor INTO @table, @lvl;

WHILE @@FETCH_STATUS = 0
BEGIN
    DECLARE @rows INT, @cols NVARCHAR(MAX), @vals NVARCHAR(MAX), @hasIdentity BIT;

    SELECT @rows = SUM(p.rows)
    FROM sys.tables t JOIN sys.partitions p ON p.object_id = t.object_id AND p.index_id IN (0,1)
    WHERE t.name = @table;

    IF @rows > 0
    BEGIN
        SELECT @hasIdentity = CASE WHEN EXISTS (
            SELECT 1 FROM sys.identity_columns ic
            JOIN sys.tables t ON t.object_id = ic.object_id WHERE t.name = @table) THEN 1 ELSE 0 END;

        /* Column list, and the expression that renders each value as SQL literal text. */
        SELECT
            @cols = STRING_AGG(QUOTENAME(c.name), ', ') WITHIN GROUP (ORDER BY c.column_id),
            @vals = STRING_AGG(
                CASE
                    WHEN ty.name IN ('char','varchar','nchar','nvarchar','text','ntext','xml','sysname')
                        THEN 'ISNULL(''N'''''' + REPLACE(CAST(' + QUOTENAME(c.name) + ' AS NVARCHAR(MAX)), '''''''', '''''''''''') + '''''''', ''NULL'')'
                    WHEN ty.name IN ('datetime','datetime2','smalldatetime','date','time','datetimeoffset')
                        THEN 'ISNULL('''''''' + CONVERT(NVARCHAR(40), ' + QUOTENAME(c.name) + ', 127) + '''''''', ''NULL'')'
                    WHEN ty.name = 'uniqueidentifier'
                        THEN 'ISNULL('''''''' + CAST(' + QUOTENAME(c.name) + ' AS NVARCHAR(40)) + '''''''', ''NULL'')'
                    WHEN ty.name IN ('binary','varbinary','image')
                        THEN 'ISNULL(CONVERT(NVARCHAR(MAX), ' + QUOTENAME(c.name) + ', 1), ''NULL'')'
                    WHEN ty.name = 'bit'
                        THEN 'ISNULL(CAST(CAST(' + QUOTENAME(c.name) + ' AS TINYINT) AS NVARCHAR(1)), ''NULL'')'
                    ELSE
                        'ISNULL(CAST(' + QUOTENAME(c.name) + ' AS NVARCHAR(MAX)), ''NULL'')'
                END, ' + '', '' + ') WITHIN GROUP (ORDER BY c.column_id)
        FROM sys.columns c
        JOIN sys.types ty ON ty.user_type_id = c.user_type_id
        JOIN sys.tables t ON t.object_id = c.object_id
        WHERE t.name = @table
          AND c.is_computed = 0
          AND ty.name <> 'timestamp';   /* rowversion is server-generated and rejects an insert */

        INSERT INTO @out (Line) VALUES ('/* ---- ' + @table + ' (' + CAST(@rows AS NVARCHAR(10)) + ' rows) ---- */');

        IF @hasIdentity = 1
            INSERT INTO @out (Line) VALUES ('SET IDENTITY_INSERT ' + QUOTENAME(@table) + ' ON;');

        DECLARE @sql NVARCHAR(MAX) =
            'SELECT ''INSERT INTO ' + QUOTENAME(@table) + ' (' + @cols + ') VALUES ('' + ' + @vals + ' + '');'' FROM ' + QUOTENAME(@table) + ';';

        INSERT INTO @out (Line) EXEC sp_executesql @sql;

        IF @hasIdentity = 1
            INSERT INTO @out (Line) VALUES ('SET IDENTITY_INSERT ' + QUOTENAME(@table) + ' OFF;');

        INSERT INTO @out (Line) VALUES ('');
    END

    FETCH NEXT FROM plan_cursor INTO @table, @lvl;
END

CLOSE plan_cursor;
DEALLOCATE plan_cursor;

INSERT INTO @out (Line) VALUES
    ('COMMIT;'),
    ('/* end */');

SELECT Line FROM @out ORDER BY Seq;
